key.key.*:
  type: config_entity
  label: 'Key config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    key_provider:
      type: string
      label: Key Provider
    key_settings:
      type: key.key_provider.plugin.[id]
      label: 'Key Settings'

key_provider:
  type: mapping
  label: 'Key provider settings'
  mapping:
    id:
      type: string
      label: 'ID'

key.key_provider.plugin.*:
  type: key_provider

key.key_provider.plugin.key_provider_simple:
  type: key_provider
  label: 'Simple Key'
  mapping:
    simple_key_value:
      type: string
      label: 'Key Value'

key.key_provider.plugin.key_provider_file:
  type: key_provider
  label: 'Simple Key'
  mapping:
    file_key_location:
      type: string
      label: 'File Location'
