key.key.*:
  type: config_entity
  label: 'Key config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    key_type:
      type: string
      label: Key Type
    key_settings:
      type: key.key_type.plugin.[id]
      label: 'Key Settings'

key_type:
  type: mapping
  label: 'Key type settings'
  mapping:
    id:
      type: string
      label: 'ID'

key.key_type.plugin.*:
  type: key_type

key.key_type.plugin.key_type_simple:
  type: key_type
  label: 'Simple Key'
  mapping:
    simple_key_value:
      type: string
      label: 'Key Value'
